version: '2'

services:
  slack-presence:
    build: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - "9222:9222"
      - "8080:8080"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./chrome:/opt/app/chrome
      - ./options.json:/opt/app/options.json
