version: '3'

services:
  slack-presence:
    image: marchukd/slack-presence
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 1024m
        reservations:
          cpus: '0.1'
          memory: 512m
    ports:
      - "9222:9222"
      - "9333:9333"
    environment:
      - PUSHOVER_USER_KEY=
      - PUSHOVER_API_TOKEN=
      - TZ=Europe/Kiev
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./chrome:/opt/app/chrome
      - ./options.json:/opt/app/options.json
