name: Push to DockerHub on every git tag
on:
  push:
    tags:
      - 'v*'
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Docker build
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:latest --tag $DOCKER_USER/$REPO_NAME:${{ steps.get_version.outputs.VERSION }}
      - name: Docker push
        run: docker push --all-tags $DOCKER_USER/$REPO_NAME:${{ steps.get_version.outputs.VERSION }}
